apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
  POSTGRES_PORT : '${POSTGRES_PORT}'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  MONGO_NOTEFLOW_USERNAME: ${MONGO_NOTEFLOW_USERNAME}
  MONGO_NOTEFLOW_PASSWORD: ${MONGO_NOTEFLOW_PASSWORD}
  MONGO_INITDB_DATABASE: ${MONGO_DB}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:



---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
    MONGO_HOST: '$MONGO_HOST'
    MONGO_DB: $MONGO_DB
    MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
    MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    MONGO_NOTEFLOW_USERNAME: $MONGO_NOTEFLOW_USERNAME
    MONGO_NOTEFLOW_PASSWORD: $MONGO_NOTEFLOW_PASSWORD
    MONGO_PORT: '$MONGO_PORT'
    PHOTO_FS: $PHOTO_FS

    POSTGRES_HOST: $POSTGRES_HOST
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_PORT: '$POSTGRES_PORT'

    REDIS_HOST: $REDIS_HOST
    REDIS_PORT: '$REDIS_PORT'
    REDIS_SESSION_HOST: $REDIS_SESSION_HOST
    REDIS_SESSION_PORT: '$REDIS_SESSION_PORT'
    REDIS_ACCOUNT: $REDIS_ACCOUNT
    REDIS_PASSWORD: $REDIS_PASSWORD

    S3_BUCKET_REGION: $S3_BUCKET_REGION

    EMAIL_HOST: $EMAIL_HOST
    EMAIL_USER: $EMAIL_USER
    EMAIL_PASSWORD: $EMAIL_PASSWORD
    REFRESH_TOKEN: $REFRESH_TOKEN
    CLIENT_SECRET: $CLIENT_SECRET
    CLIENT_ID: $CLIENT_ID
    VITE_NOTEFLOW_BACKEND: ${NOTEFLOW_BACKEND}
    VITE_NOTEFLOW_PORT: '${BACKEND_EXPOSE_PORT}'
    VITE_DEV: '${VITE_DEV}'
    FRONTEND_EXPOSE_PORT: '${FRONTEND_EXPOSE_PORT}'
